### ISSUE TITLE
What's Next ?

### ISSUE THREAD

**Issue by MehmetUzel** [samikarakul/catordog#5]
It's been days since you didn't contribute any project.

What's the plan ?
-New Project
-Improving this one

**Comment by samikarakul** [comment]
Hey thanks for your question!

Both actually.
This project still needs to speed up and some ui need to be change especially homepage. 
Unfortunately i don't have a project idea for now. I am planning to make small project to use on different projects rather than a full project.

**Comment by MehmetUzel** [comment]
Maybe it's time to make a portfolio website ?

**Comment by samikarakul** [comment]
I was thinking to make a portfolio website for some time. You're right, it is time to make one! Thank you!
